import { v } from 'convex/values'
import { internalMutation, internalQuery } from './_generated/server'

const roleValidator = v.union(
  v.literal('user'),
  v.literal('assistant'),
  v.literal('tool'),
)

/**
 * Purpose: Fetches the saved soul configuration for a user before an AI response is generated.
 * Function type: internalQuery
 * Args:
 * - userId: v.string()
 */
export const getSoulByUserId = internalQuery({
  args: { userId: v.string() },
  handler: async (ctx, args) => {
    return await ctx.db
      .query('souls')
      .withIndex('userId', (q) => q.eq('userId', args.userId))
      .unique()
  },
})

/**
 * Purpose: Loads recent non-tool conversation turns to build model context for the assistant.
 * Function type: internalQuery
 * Args:
 * - userId: v.string()
 * - limit: v.optional(v.number())
 */
export const getConversationHistory = internalQuery({
  args: { userId: v.string(), limit: v.optional(v.number()) },
  handler: async (ctx, args) => {
    const limit = Math.min(100, Math.max(1, args.limit ?? 50))
    const scanLimit = Math.min(400, Math.max(limit * 4, 80))
    const rows = await ctx.db
      .query('messages')
      .withIndex('userId_createdAt', (q) => q.eq('userId', args.userId))
      .order('desc')
      .take(scanLimit)
    return rows
      .filter(
        (row) =>
          row.role !== 'tool' && !(row.role === 'assistant' && row.toolCallId),
      )
      .slice(0, limit)
      .reverse()
      .map((row) => ({
        role: row.role as 'user' | 'assistant',
        content: row.content,
      }))
  },
})

/**
 * Purpose: Returns the user's core memory facts as key-value pairs for prompt construction.
 * Function type: internalQuery
 * Args:
 * - userId: v.string()
 */
export const getCoreMemories = internalQuery({
  args: { userId: v.string() },
  handler: async (ctx, args) => {
    const rows = await ctx.db
      .query('coreMemories')
      .withIndex('userId_key', (q) => q.eq('userId', args.userId))
      .take(50)
    return rows.map((row) => ({ key: row.key, value: row.value }))
  },
})

/**
 * Purpose: Stores a single conversation message generated by the app, Telegram bot, or tools.
 * Function type: internalMutation
 * Args:
 * - userId: v.string()
 * - role: roleValidator
 * - content: v.string()
 * - toolName: v.optional(v.string())
 * - toolCallId: v.optional(v.string())
 */
export const saveMessage = internalMutation({
  args: {
    userId: v.string(),
    role: roleValidator,
    content: v.string(),
    toolName: v.optional(v.string()),
    toolCallId: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    await ctx.db.insert('messages', {
      userId: args.userId,
      role: args.role,
      content: args.content,
      toolName: args.toolName,
      toolCallId: args.toolCallId,
      createdAt: Date.now(),
    })
  },
})

/**
 * Purpose: Upserts auto-extracted core memories discovered from user conversations.
 * Function type: internalMutation
 * Args:
 * - userId: v.string()
 * - facts: v.array( v.object({ key: v.string(), value: v.string(), category: v.optional(v.string()), }), )
 */
export const upsertAutoExtractedCoreMemories = internalMutation({
  args: {
    userId: v.string(),
    facts: v.array(
      v.object({
        key: v.string(),
        value: v.string(),
        category: v.optional(v.string()),
      }),
    ),
  },
  handler: async (ctx, args) => {
    const now = Date.now()
    let changed = 0
    let memoryCount = (
      await ctx.db
        .query('coreMemories')
        .withIndex('userId', (q) => q.eq('userId', args.userId))
        .take(50)
    ).length

    for (const fact of args.facts) {
      const key = fact.key.trim().slice(0, 50).toLowerCase()
      const value = fact.value.trim().slice(0, 200)
      if (!key || !value) continue

      const existing = await ctx.db
        .query('coreMemories')
        .withIndex('userId_key', (q) =>
          q.eq('userId', args.userId).eq('key', key),
        )
        .unique()

      if (existing) {
        if (existing.value !== value || existing.category !== fact.category) {
          await ctx.db.patch('coreMemories', existing._id, {
            value,
            category: fact.category,
            updatedAt: now,
          })
          changed += 1
        }
        continue
      }

      if (memoryCount >= 50) break

      await ctx.db.insert('coreMemories', {
        userId: args.userId,
        key,
        value,
        category: fact.category,
        source: 'auto',
        createdAt: now,
        updatedAt: now,
      })
      changed += 1
      memoryCount += 1
    }

    return changed
  },
})
