const MODEL_IDS = [
  'alibaba/qwen-3-32b',
  'alibaba/qwen3-coder-30b-a3b',
  'alibaba/qwen3-max-thinking',
  'alibaba/qwen3-vl-235b-a22b-instruct',
  'alibaba/qwen3.5-flash',
  'alibaba/qwen3.5-plus',
  'alibaba/qwen3.6-27b',
  'alibaba/qwen-3.6-max-preview',
  'alibaba/qwen3.6-plus',
  'alibaba/qwen-3-235b',
  'alibaba/qwen3-235b-a22b-thinking',
  'alibaba/qwen3-coder',
  'alibaba/qwen3-coder-next',
  'alibaba/qwen3-coder-plus',
  'alibaba/qwen3-embedding-0.6b',
  'alibaba/qwen3-embedding-4b',
  'alibaba/qwen3-embedding-8b',
  'alibaba/qwen3-max',
  'alibaba/qwen3-max-preview',
  'alibaba/qwen3-next-80b-a3b-instruct',
  'alibaba/qwen3-next-80b-a3b-thinking',
  'alibaba/qwen3-vl-instruct',
  'alibaba/qwen3-vl-thinking',
  'alibaba/qwen-3-14b',
  'alibaba/qwen-3-30b',
  'amazon/nova-2-lite',
  'amazon/nova-lite',
  'amazon/nova-micro',
  'amazon/nova-pro',
  'amazon/titan-embed-text-v2',
  'anthropic/claude-3-haiku',
  'anthropic/claude-3.5-haiku',
  'anthropic/claude-haiku-4.5',
  'anthropic/claude-opus-4',
  'anthropic/claude-opus-4.1',
  'anthropic/claude-opus-4.5',
  'anthropic/claude-opus-4.6',
  'anthropic/claude-opus-4.7',
  'anthropic/claude-sonnet-4',
  'anthropic/claude-sonnet-4.5',
  'anthropic/claude-sonnet-4.6',
  'arcee-ai/trinity-large-preview',
  'arcee-ai/trinity-large-thinking',
  'arcee-ai/trinity-mini',
  'bfl/flux-pro-1.0-fill',
  'bfl/flux-kontext-max',
  'bfl/flux-kontext-pro',
  'bfl/flux-2-flex',
  'bfl/flux-2-klein-4b',
  'bfl/flux-2-klein-9b',
  'bfl/flux-2-max',
  'bfl/flux-2-pro',
  'bfl/flux-pro-1.1',
  'bfl/flux-pro-1.1-ultra',
  'bytedance/seed-1.8',
  'bytedance/seed-1.6',
  'bytedance/seedream-4.0',
  'bytedance/seedream-4.5',
  'bytedance/seedream-5.0-lite',
  'cohere/rerank-v3.5',
  'cohere/rerank-v4-fast',
  'cohere/rerank-v4-pro',
  'cohere/command-a',
  'cohere/embed-v4.0',
  'deepseek/deepseek-r1',
  'deepseek/deepseek-v3',
  'deepseek/deepseek-v3.1',
  'deepseek/deepseek-v3.1-terminus',
  'deepseek/deepseek-v3.2',
  'deepseek/deepseek-v3.2-thinking',
  'deepseek/deepseek-v4-flash',
  'deepseek/deepseek-v4-pro',
  'google/gemini-2.0-flash',
  'google/gemini-2.0-flash-lite',
  'google/gemini-2.5-flash',
  'google/gemini-2.5-flash-lite',
  'google/gemini-2.5-flash-lite-preview-09-2025',
  'google/gemini-2.5-flash-preview-09-2025',
  'google/gemini-2.5-pro',
  'google/gemini-3-flash',
  'google/gemini-3-pro-preview',
  'google/gemini-3.1-flash-image-preview',
  'google/gemini-3.1-flash-lite',
  'google/gemini-3.1-flash-lite-preview',
  'google/gemini-3.1-pro-preview',
  'google/gemini-embedding-001',
  'google/gemini-embedding-2',
  'google/gemma-4-26b-a4b-it',
  'google/gemma-4-31b-it',
  'google/imagen-4.0-generate-001',
  'google/imagen-4.0-fast-generate-001',
  'google/imagen-4.0-ultra-generate-001',
  'google/gemini-2.5-flash-image',
  'google/gemini-3-pro-image',
  'google/text-embedding-005',
  'google/text-multilingual-embedding-002',
  'inception/mercury-2',
  'inception/mercury-coder-small',
  'interfaze/interfaze-beta',
  'kwaipilot/kat-coder-pro-v2',
  'kwaipilot/kat-coder-pro-v1',
  'meituan/longcat-flash-chat',
  'meituan/longcat-flash-thinking-2601',
  'meta/llama-3.1-70b',
  'meta/llama-3.1-8b',
  'meta/llama-3.2-11b',
  'meta/llama-3.2-1b',
  'meta/llama-3.2-3b',
  'meta/llama-3.2-90b',
  'meta/llama-3.3-70b',
  'meta/llama-4-maverick',
  'meta/llama-4-scout',
  'minimax/minimax-m2',
  'minimax/minimax-m2.1',
  'minimax/minimax-m2.1-lightning',
  'minimax/minimax-m2.5',
  'minimax/minimax-m2.5-highspeed',
  'minimax/minimax-m2.7',
  'minimax/minimax-m2.7-highspeed',
  'mistral/codestral-embed',
  'mistral/devstral-2',
  'mistral/devstral-small',
  'mistral/devstral-small-2',
  'mistral/magistral-medium',
  'mistral/magistral-small',
  'mistral/ministral-14b',
  'mistral/ministral-3b',
  'mistral/ministral-8b',
  'mistral/codestral',
  'mistral/mistral-embed',
  'mistral/mistral-large-3',
  'mistral/mistral-medium',
  'mistral/mistral-nemo',
  'mistral/mistral-small',
  'mistral/pixtral-12b',
  'mistral/pixtral-large',
  'moonshotai/kimi-k2',
  'moonshotai/kimi-k2-thinking',
  'moonshotai/kimi-k2-thinking-turbo',
  'moonshotai/kimi-k2-turbo',
  'moonshotai/kimi-k2.5',
  'moonshotai/kimi-k2.6',
  'morph/morph-v3-fast',
  'morph/morph-v3-large',
  'nvidia/nemotron-3-nano-30b-a3b',
  'nvidia/nemotron-3-super-120b-a12b',
  'nvidia/nemotron-nano-12b-v2-vl',
  'nvidia/nemotron-nano-9b-v2',
  'openai/gpt-4o-mini-search-preview',
  'openai/gpt-5-chat',
  'openai/gpt-5.1-codex-max',
  'openai/gpt-5.1-codex-mini',
  'openai/gpt-5.1-thinking',
  'openai/gpt-5.2',
  'openai/gpt-5.2-pro',
  'openai/gpt-5.2-chat',
  'openai/gpt-5.2-codex',
  'openai/gpt-5.3-codex',
  'openai/gpt-5.4',
  'openai/gpt-5.4-mini',
  'openai/gpt-5.4-nano',
  'openai/gpt-5.4-pro',
  'openai/gpt-5.5',
  'openai/gpt-5.5-pro',
  'openai/gpt-image-1',
  'openai/gpt-image-1-mini',
  'openai/gpt-image-1.5',
  'openai/gpt-image-2',
  'openai/gpt-oss-120b',
  'openai/gpt-oss-20b',
  'openai/gpt-oss-safeguard-20b',
  'openai/gpt-3.5-turbo',
  'openai/gpt-3.5-turbo-instruct',
  'openai/gpt-4-turbo',
  'openai/gpt-4.1',
  'openai/gpt-4.1-mini',
  'openai/gpt-4.1-nano',
  'openai/gpt-4o',
  'openai/gpt-4o-mini',
  'openai/gpt-5',
  'openai/gpt-5-mini',
  'openai/gpt-5-nano',
  'openai/gpt-5-pro',
  'openai/gpt-5-codex',
  'openai/gpt-5.1-instant',
  'openai/gpt-5.1-codex',
  'openai/gpt-5.3-chat',
  'openai/o1',
  'openai/o3',
  'openai/o3-pro',
  'openai/o3-deep-research',
  'openai/o3-mini',
  'openai/o4-mini',
  'openai/text-embedding-3-large',
  'openai/text-embedding-3-small',
  'openai/text-embedding-ada-002',
  'perplexity/sonar',
  'perplexity/sonar-pro',
  'perplexity/sonar-reasoning-pro',
  'prodia/flux-fast-schnell',
  'recraft/recraft-v2',
  'recraft/recraft-v3',
  'recraft/recraft-v4',
  'recraft/recraft-v4-pro',
  'recraft/recraft-v4.1',
  'recraft/recraft-v4.1-pro',
  'recraft/recraft-v4.1-utility',
  'recraft/recraft-v4.1-utility-pro',
  'voyage/voyage-3.5',
  'voyage/voyage-3.5-lite',
  'voyage/voyage-4',
  'voyage/voyage-4-large',
  'voyage/voyage-4-lite',
  'voyage/voyage-code-2',
  'voyage/voyage-code-3',
  'voyage/voyage-finance-2',
  'voyage/voyage-law-2',
  'voyage/rerank-2.5',
  'voyage/rerank-2.5-lite',
  'voyage/voyage-3-large',
  'xai/grok-3',
  'xai/grok-3-fast',
  'xai/grok-3-mini',
  'xai/grok-3-mini-fast',
  'xai/grok-4',
  'xai/grok-4-fast-non-reasoning',
  'xai/grok-4-fast-reasoning',
  'xai/grok-4.1-fast-non-reasoning',
  'xai/grok-4.1-fast-reasoning',
  'xai/grok-4.20-non-reasoning-beta',
  'xai/grok-4.20-reasoning-beta',
  'xai/grok-4.20-multi-agent-beta',
  'xai/grok-4.20-multi-agent',
  'xai/grok-4.20-non-reasoning',
  'xai/grok-4.20-reasoning',
  'xai/grok-4.3',
  'xai/grok-code-fast-1',
  'xai/grok-imagine-image',
  'xai/grok-imagine-image-pro',
  'xiaomi/mimo-v2.5',
  'xiaomi/mimo-v2-flash',
  'xiaomi/mimo-v2-pro',
  'xiaomi/mimo-v2.5-pro',
  'zai/glm-4.5',
  'zai/glm-4.5-air',
  'zai/glm-4.5v',
  'zai/glm-4.6',
  'zai/glm-4.7',
  'zai/glm-4.7-flash',
  'zai/glm-4.7-flashx',
  'zai/glm-5',
  'zai/glm-5-turbo',
  'zai/glm-5.1',
  'zai/glm-5v-turbo',
  'zai/glm-4.6v',
  'zai/glm-4.6v-flash',
] as const

export const MODEL_OPTIONS = MODEL_IDS.map((modelId) => ({
  label: modelId,
  value: modelId,
})) as ReadonlyArray<{ label: string; value: (typeof MODEL_IDS)[number] }>

export const SEARCH_PROVIDER_OPTIONS = [
  { label: 'Exa (default)', value: 'exa' },
  { label: 'Tavily', value: 'tavily' },
] as const

const COMMON_TIMEZONE_OPTIONS = [
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'America/Anchorage',
  'Pacific/Honolulu',
  'America/Toronto',
  'America/Vancouver',
  'America/Sao_Paulo',
  'America/Argentina/Buenos_Aires',
  'America/Mexico_City',
  'Europe/London',
  'Europe/Paris',
  'Europe/Berlin',
  'Europe/Moscow',
  'Europe/Istanbul',
  'Africa/Cairo',
  'Africa/Lagos',
  'Africa/Johannesburg',
  'Africa/Nairobi',
  'Asia/Dubai',
  'Asia/Kolkata',
  'Asia/Shanghai',
  'Asia/Tokyo',
  'Asia/Seoul',
  'Asia/Singapore',
  'Asia/Hong_Kong',
  'Australia/Sydney',
  'Australia/Melbourne',
  'Pacific/Auckland',
]

export type SearchProvider = 'exa' | 'tavily'

export type SoulPreferences = {
  id: string
  systemPrompt: string
  modelPreference: string | null
  researchModelPreference: string | null
  searchProvider: SearchProvider | null
  researchDepth: number | null
  researchBreadth: number | null
  timezone: string | null
  createdAt: string
  updatedAt: string
}

export type PreferenceFormState = {
  model: string
  researchModel: string
  researchDepth: number
  researchBreadth: number
  searchProvider: SearchProvider
  timezone: string
}

export const DEFAULT_SYSTEM_PROMPT =
  'You are a helpful personal assistant. You are friendly, concise, and action-oriented.'

export function createPreferenceFormState(
  soul: SoulPreferences | null | undefined,
): PreferenceFormState {
  return {
    model: soul?.modelPreference ?? '',
    researchModel: soul?.researchModelPreference ?? '',
    researchDepth: soul?.researchDepth ?? 2,
    researchBreadth: soul?.researchBreadth ?? 3,
    searchProvider: soul?.searchProvider ?? 'exa',
    timezone: soul?.timezone ?? '',
  }
}

export function arePreferenceFormsEqual(
  left: PreferenceFormState,
  right: PreferenceFormState,
) {
  return (
    left.model === right.model &&
    left.researchModel === right.researchModel &&
    left.researchDepth === right.researchDepth &&
    left.researchBreadth === right.researchBreadth &&
    left.searchProvider === right.searchProvider &&
    left.timezone === right.timezone
  )
}

export function getTimezoneOptions() {
  try {
    return Intl.supportedValuesOf('timeZone')
  } catch {
    return COMMON_TIMEZONE_OPTIONS
  }
}
