/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTasksRouteImport } from './routes/dashboard/tasks'
import { Route as DashboardSoulsRouteImport } from './routes/dashboard/souls'
import { Route as DashboardResearchRouteImport } from './routes/dashboard/research'
import { Route as DashboardPreferencesRouteImport } from './routes/dashboard/preferences'
import { Route as DashboardMemoriesRouteImport } from './routes/dashboard/memories'
import { Route as DashboardIntegrationsRouteImport } from './routes/dashboard/integrations'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSoulsRoute = DashboardSoulsRouteImport.update({
  id: '/souls',
  path: '/souls',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResearchRoute = DashboardResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPreferencesRoute = DashboardPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMemoriesRoute = DashboardMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/memories': typeof DashboardMemoriesRoute
  '/dashboard/preferences': typeof DashboardPreferencesRoute
  '/dashboard/research': typeof DashboardResearchRoute
  '/dashboard/souls': typeof DashboardSoulsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/memories': typeof DashboardMemoriesRoute
  '/dashboard/preferences': typeof DashboardPreferencesRoute
  '/dashboard/research': typeof DashboardResearchRoute
  '/dashboard/souls': typeof DashboardSoulsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/memories': typeof DashboardMemoriesRoute
  '/dashboard/preferences': typeof DashboardPreferencesRoute
  '/dashboard/research': typeof DashboardResearchRoute
  '/dashboard/souls': typeof DashboardSoulsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/account'
    | '/dashboard/integrations'
    | '/dashboard/memories'
    | '/dashboard/preferences'
    | '/dashboard/research'
    | '/dashboard/souls'
    | '/dashboard/tasks'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/account'
    | '/dashboard/integrations'
    | '/dashboard/memories'
    | '/dashboard/preferences'
    | '/dashboard/research'
    | '/dashboard/souls'
    | '/dashboard/tasks'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/account'
    | '/dashboard/integrations'
    | '/dashboard/memories'
    | '/dashboard/preferences'
    | '/dashboard/research'
    | '/dashboard/souls'
    | '/dashboard/tasks'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/souls': {
      id: '/dashboard/souls'
      path: '/souls'
      fullPath: '/dashboard/souls'
      preLoaderRoute: typeof DashboardSoulsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/research': {
      id: '/dashboard/research'
      path: '/research'
      fullPath: '/dashboard/research'
      preLoaderRoute: typeof DashboardResearchRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/preferences': {
      id: '/dashboard/preferences'
      path: '/preferences'
      fullPath: '/dashboard/preferences'
      preLoaderRoute: typeof DashboardPreferencesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/memories': {
      id: '/dashboard/memories'
      path: '/memories'
      fullPath: '/dashboard/memories'
      preLoaderRoute: typeof DashboardMemoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/integrations': {
      id: '/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardMemoriesRoute: typeof DashboardMemoriesRoute
  DashboardPreferencesRoute: typeof DashboardPreferencesRoute
  DashboardResearchRoute: typeof DashboardResearchRoute
  DashboardSoulsRoute: typeof DashboardSoulsRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardMemoriesRoute: DashboardMemoriesRoute,
  DashboardPreferencesRoute: DashboardPreferencesRoute,
  DashboardResearchRoute: DashboardResearchRoute,
  DashboardSoulsRoute: DashboardSoulsRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
